# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 853a929be8a19cfd6e9fc84bea4eefb22fe4397cd449314dff6c89c6ecaf6f2ec4f9b3e887fb913e80ee682ff3acca2a0dfbaed2dd9b99cfad3d417114f8e4cf

test:
  secret_key_base: 7d017a8d3cd2868183d388344e70141dd656b882c435dfced1fea05fd37ff14ddba718cbd3e96d42c56a6d80fb5307f4d4e4730663420438ea4961393ac56563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
